package com.urlshortener.orchestrator.domain;

public enum EventType {
    RUN_STARTED,
    RUN_PAUSED,
    RUN_RESUMED,
    RUN_CANCELLED,
    RUN_COMPLETED,
    RUN_FAILED,
    NODE_DISPATCHED,
    NODE_AWAITING_APPROVAL,
    APPROVAL_GRANTED,
    APPROVAL_REJECTED,
    NODE_COMPLETED,
    NODE_FAILED,
    RETRY_ATTEMPTED,
    RETRY_EXHAUSTED,
    FALLBACK_TRIGGERED,
    ROLLBACK_TRIGGERED,
    POLICY_VIOLATION,
    REPLAN_TRIGGERED,
    NODE_SKIPPED
}
